title: Discloud CLI
description: A fast option to manage your apps on Discloud.
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
